### ISSUE TITLE
Setup The Kanban

### ISSUE THREAD

**Issue by Tobinchilongo** [Thermiee/catalog-of-my-things#7]
## During this activity as a group we had set up the Kanban board and shared activities according to the project's requirements

- We Are Two(2) In Our Team

This is how we shared the activities:
Team member 1 **[Tobin](https://github.com/Tobinchilongo)**
Team member 3 **[Thermiee](https://github.com/Thermiee)**

🚀  [Link to the Repository](https://github.com/Thermiee/catalog-of-my-things)

**Comment by Emmyn5600** [comment]
Hi @Thermiee and @Tobinchilongo 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

- [ ] N/A.

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Tobinchilongo** [comment]
Hi @Emmyn5600 ,

Thank you very much for the positive review 🚀
